name: Build all
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: pnpm-store
      with:
        path: ~/.pnpm-store/v3
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.9.1
    - run: pnpm i --frozen-lockfile
    - run: pnpm build
